### PR TITLE
Update auth/sync urls

### PR DESCRIPTION
**Pull request by SaWey**
The URLS of the API seem to have been updated.

This should fix some open issues:
#47
#48 
#49 
#51

### CODE REVIEW

**Comment by ioanac85** [comment]
Hi all!
I don't have a CS editor, could you please attach the files so i can download them with the modified links? I get the error when trying to register OneNote with remarkable. Thanks!

**Comment by SaWey** [comment]
Hi

I was hoping the PR would be merged, but it seems the current owner is not able to do so.
For the time being, I published a release that should fix the current version.

https://github.com/SaWey/reMarkableSync/releases/tag/3.0.1

**Comment by carlo0501** [comment]
Thanks Sander

Your temporary correction allows me to make one step forward.
Now I can see the list of the documents, but when I try to fetch one I
always get an error message: "Value cannot be null. Parameter name: source."
This happens irrespectively from the option Text/Graphics/Both.
Hopefully you can further help...

 Carlo

**Comment by SaWey** [comment]
Hi

Yes, that is because of the new layout of the pages internally.
With Remarkable V3 they updated the format and this app can't handle that yet.

**Comment by carlo0501** [comment]
Too bad!Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Sander Weyens ***@***.***> Data: 07/03/23  19:15  (GMT+01:00) A: jamesf91/reMarkableSync ***@***.***> Cc: carlo0501 ***@***.***>, Comment ***@***.***> Oggetto: Re: [jamesf91/reMarkableSync] Update auth/sync urls (PR #52) 
Hi
Yes, that is because of the new layout of the pages internally.
With Remarkable V3 they updated the format and this app can't handle that yet.

**Comment by danoflorida** [comment]
The current version from the original publisher (jamesf91) isn't designed to handle reMarkable v3.  In order to use the add-in, you need to roll-back to v2.  Using the "switch.sh" script I was able to boot back to the previous tablet v2.15.1.1189 since it's saved on the tablet in a separate partition. I unpaired with the cloud and re-established sync using the downgraded OS.  Also remember to turn off the automatic updates on your tablet.  The fix from SaWey resolves the cloud sync issue as long as you're still using the tablet v2 version.  I believe the revision that's needed from jamesf91 for reMarkable v3 compatibility is a significant effort.  For now, I'm staying with v2 since most important feature to me is OneNote connectivity.

**Comment by NetMare00** [comment]
Hi @SaWey,

thanks for making the fix for the url change. Can you please also publish the 32bit version? Add-In is not showing up on my 32bit version of OneNote...
Would be great!

NetMare

**Comment by SaWey** [comment]
I tried to rewrite a part of this to make it work with the new reMarkable file version as well.
The beta release can be found here: 
https://github.com/SaWey/reMarkableSync/releases/tag/4.0.0-beta

**Comment by seanym007** [comment]
Tested partial fix version 3.3 - page was imported but still got an error - nearly there!
"Error importing document from reMarkable.
Object reference not set to an instance of an object"

Thanks to all contributing - this addon really is a life saver! - thank-you!

**Comment by SaWey** [comment]
Any extra info on the error? There is not a lot of debug logging yet.
- Import of 1 or more pages
- Was part of the import successful?
- Cloud / local connection

There is not a lot of debug logging yet, but could you enable it and send me the log file?
Here are the instructions on how to enable debug logging:
https://github.com/SaWey/reMarkableSync/wiki#setting-up-debug-logging

**Comment by seanym007** [comment]
Hey Sanders,

Yes more than happy to help!

So, tried to enable debugging but no log being produced? I’ve added the additional config and restarted OneNote? Anything else I’m missing? I’m assuming the log will be written to the directory that sync in installed to?

Also:
Import, the page was imported BUT completely blank apart from the title. I can see new pages in the directory structure for import and able to select but then as I say the resultant page is blank, i.e. no content is actually imported.

And this error:
***@***.***

I’ll keep trying to get the debugging log to work..

Thanks

Sean M

**Comment by SaWey** [comment]
> 

Hi Sean,

It should indeed end up in the same folder.
Are you sure you edited 'RemarkableSync.OnenoteAddin.exe.config' and not 'RemarkableSync.dll.config'

Another possible issue could be permissions. 
You could set the path of the logging file to something different in
```XML
<target name="logfile" xsi:type="File" fileName="C:\PATH_TO\log.txt" />
```

Are you trying to import text, image or both?

**Comment by seanym007** [comment]
Ahh good spot on the permissions 😊

Log attached!

I’ve tried all 3 options.. same result!

Also – this is the page I’m trying to import ->

***@***.***

Kind Regards

Sean M

**Comment by seanym007** [comment]
So..

It looks like the issue I have is the code I used to set up sync has been invalidated – Odd that sync still lets me list the directory, but gives me an unauthorised when I try and import.

Frustratingly I cannot see how I can get remarkable to generate me a new code ☹ - seems I’ll need to log a support ticket with them..

Sean M

From: Meyers, Sean ***@***.***>
Sent: 02 May 2023 12:33
To: jamesf91/reMarkableSync ***@***.***>; jamesf91/reMarkableSync ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [jamesf91/reMarkableSync] Update auth/sync urls (PR #52)

Ahh good spot on the permissions 😊

Log attached!

I’ve tried all 3 options.. same result!

Also – this is the page I’m trying to import ->

***@***.***

Kind Regards

Sean M

**Comment by SaWey** [comment]
Sean

It is not the reMarkable sync token, as it can download the content:
```
2023-05-02 12:31:42.4658|DEBUG|RemarkableSync.RmDocument|Downloaded 1 of 4 files
2023-05-02 12:31:42.4658|DEBUG|RemarkableSync.RmDocument|Finished creating downloaded doc for id: 0591617a-aa1a-4ef6-9cad-e20f90dbf83d
2023-05-02 12:31:42.4658|DEBUG|RemarkableSync.RmDocument|Reading content file C:\Users\sean.meyers\AppData\Local\Temp\0591617a-aa1a-4ef6-9cad-e20f90dbf83d\0591617a-aa1a-4ef6-9cad-e20f90dbf83d.content for page mapping
2023-05-02 12:31:42.5057|DEBUG|RemarkableSync.OnenoteAddin.RmDownloadForm|document downloaded
```
It is with the MyScript handwriting recognition things go wrong. 
The add-on is not finding the settings for this service, and just tries to continue:
```
2023-05-02 12:31:42.5057|ERROR|RemarkableSync.WinRegistryConfigStore|Getting value from registry for config "appkey" failed
2023-05-02 12:31:42.5057|ERROR|RemarkableSync.WinRegistryConfigStore|Getting value from registry for config "hmackey" failed
2023-05-02 12:31:42.5057|DEBUG|RemarkableSync.document.v6.RmPageBinaryV6|Block header: Length 25, minVersion 1, curVersion 1, blockType 9
```

Could you try to set those credentials again in the config screen?

**Comment by seanym007** [comment]
Amazing! That works perfectly!

Thank-you so much – this is an absolute life saver 😊

Sean M

**Comment by henkvandervaart** [comment]
Just to inform you / let you know that in my own local repo with C# cloud API code for reMarkable 2 I was also facing HTTP error 500 when register device. Luckily found this URL change - and changing the auth URL did resolved my HTTP error 500 - so thanks.

**Comment by jamesf91** [comment]
Hi @SaWey , Thanks for the pull request.
I'm coming back after 2 year hiatus and just trying to get back up to speed. 
Do you know what is the current state of remarkable format? Is the new parsing module in the PR still applicable to the current rm format?

I just had a quick look at rmscene and it is saying supporting v6 format. Has there really been 3 versions in the last 2 years or is it really the same as v3 but just different versioning scheme?

**Comment by SaWey** [comment]
Hi @jamesf91 
The PR should still be valid.

I have not touched the code since April 2023, so I have to catch up myself.
I think your code supported v5 format, and v6 is with the new text and such.
My repo already had some support for reading that format. 

I will also push my last unfinished changes to my fork. Really was just experimenting with the options but did not get to anything releasable.

It seems like they updated the API urls again, so currently it is not able to connect to the cloud.
Fetching the root is now located at https://internal.cloud.remarkable.com/doc/v2/files

```C#
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, "https://internal.cloud.remarkable.com/doc/v2/files");
request.Headers.Add("Authorization", "Bearer TOKEN");
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

**Comment by jamesf91** [comment]
Hi @SaWey,

Thanks for the update. The first 2 commits in the pull requests look good. I'd be happy to merge that in and use it as the basis for future work. 

I'm getting some build errors on the last commit (4c1a90f127bc08bfdbb12d2ae89d576ca3423875)
image

Note I am referencing against the master branch of [idvorkin/onom](https://github.com/idvorkin/onom). Not sure if you are using a different version with a different constructor signature for OneNoteApplication.

I suggest you move the last commit out of your develop branch onto a work in progress branch. Then I can merge this pull request and tag a new version.

**Comment by SaWey** [comment]
@jamesf91 I reversed the last commit and put those changes in a separate branch as suggested.
It is only that commit which references a change in the onom code. 
I added a constructor, but don't remember why:
`OneNoteObjectModel\OneNoteApplication.cs
`
```C#
public OneNoteApplication()
{}

public OneNoteApplication(Application interopApplication)
{
    this._interopApplication = interopApplication;
}
```

**Pull request merged**
